### PR TITLE
fixed the 283 issue "METADATA_KEY_MEDIA_ID must not be null"

### PR DESCRIPTION
**Pull request by Shkiper01**
add elvis operator

### CODE REVIEW

**Comment by nic0lette** [comment]
Thank you for the PR!

I'm hesitant to fix this issue like this because it's not so much a fix as a work-around. I'd really like to understand why it's null in the first place.

When I reason about it, the JSON file with the catalog is downloaded and handed off to `JsonSource`. This then creates a list of `MediaMetadataCompat` objects using the `MediaMetadataCompat.Builder.from` extension method defined in that file. ID is always set from the JSON, and the JSON file has IDs for every piece of music.

Since `BrowseTree` is built using the data created from `JsonSource`, it doesn't seem (at first glance) that there can be entries that have null IDs in it. (But it seems like it can, so I'd like to understand why/how)

If you can track down the root cause, I'd be more than happy to accept the PR. :)

**Comment by Shkiper01** [comment]
Ok, ill try to figure it out

**Comment by nic0lette** [comment]
Thank you! GL :)

**Comment by dturner** [comment]
I've fixed this in https://github.com/android/uamp/pull/356 and wrote up my findings in https://github.com/android/uamp/issues/316 in case you're interested.

**Pull request closed without merging**
